---
title: "qPCR_Results"
author: "Mariana Urera"
date: "2024-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ggpubr)
```


## Statistical Analysis of qPCR results

Target gene validation

```{r}
tg <- read.csv("TargetGene_qPCR_results.csv")
tg[tg == "PPARD"] <- "PPAR-D"
genes <- unique(tg$Gene)
tg$Group <- rep(NA, nrow(tg))
for (i in seq(nrow(tg))) { 

  if (tg$Condition[i] == "NSG_WT") {
    tg$Group[i] <- "Untreated Control"
  } else if (tg$Condition[i] == "SKRC39") {
    tg$Group[i] <- "Non-cachectic Control"
  } else {
    tg$Group[i] <- "Cachectic"
  }
  }

tg$Condition <- factor(tg$Condition, levels = unique(tg$Condition))
tg$Group <- factor(tg$Group, levels = unique(tg$Group))


ppard <- tg[tg$Gene == "PPAR-D",]
rara <- tg[tg$Gene == "RAR-A",]
rarb <- tg[tg$Gene == "RAR-B",]
stc1 <- tg[tg$Gene == "STC1",]
zpf609 <- tg[tg$Gene == "ZPF609",]

my_comparisons <- list( c("NSG_WT", "SKRC39"), c("SKRC39", "RXF393"))
```

# PPAR-D
```{r}
ppard_model = lm(ppard$Real_Number ~ ppard$Condition)
plot # not normal
oneway.test(Real_Number ~ Condition, ppard) # unequal variances

kruskal.test(Real_Number ~ Condition, data = ppard)
pairwise.wilcox.test(ppard$Real_Number, 
                     ppard$Condition,
                     p.adjust.method = "bonferroni")

ppard_test <- compare_means(Real_Number ~ Condition, comparisons = my_comparisons, p.adjust.method = "bonferroni", method='wilcox.test', data = ppard) %>% mutate(y.position = c(5.5, 6.5, 6))

ggplot(data = ppard, aes(y = Real_Number, x = Condition, colour = Group)) +
  geom_boxplot() + 
  geom_jitter() +
  xlab("Condition") + 
  ylab("Expression Level of PPAR-D") + 
  scale_colour_manual(values = c("forestgreen", "navy", "firebrick")) + 
  theme(legend.title = element_blank()) +
  stat_pvalue_manual(ppard_test, label = "p.adj") 

ggsave("ppard.jpg", path = "/Users/marianaurera/OneDrive - National University of Singapore/Yale-NUS/Capstone/Figures/Figure 6 (RT-qPCR)",
       width = 6.23,
      height = 3.85)
  
```

# RAR-A
```{r}
rara_model = lm(rara$Real_Number ~ rara$Condition)
plot(rara_model) # not normal
oneway.test(Real_Number ~ Condition, rara) # unequal variances

kruskal.test(Real_Number ~ Condition, data = rara)
pairwise.wilcox.test(rara$Real_Number, 
                     rara$Condition,
                     p.adjust.method = "bonferroni")

rara_test <- compare_means(Real_Number ~ Condition, comparisons = my_comparisons, p.adjust.method = "bonferroni", method='wilcox.test', data = rara) %>% mutate(y.position = c(5, 6, 5.5))

ggplot(data = rara, aes(y = Real_Number, x = Condition, colour = Group)) +
  geom_boxplot() + 
  geom_jitter() +
  xlab("Condition") + 
  ylab("Expression Level of RAR-A") + 
  scale_colour_manual(values = c("forestgreen", "navy", "firebrick")) + 
  theme(legend.title = element_blank()) +
  stat_pvalue_manual(rara_test, label = "p.adj")
ggsave("ppard.jpg", path = "/Users/marianaurera/OneDrive - National University of Singapore/Yale-NUS/Capstone/Figures/Figure 6 (RT-qPCR)",
       width = 6.23,
      height = 3.85)

  
```


# RAR-B
```{r}
rarb_model = lm(rarb$Real_Number ~ rarb$Condition)
plot(rarb_model) # not normal
oneway.test(Real_Number ~ Condition, rarb) # unequal variances

kruskal.test(Real_Number ~ Condition, data = rarb)
pairwise.wilcox.test(rarb$Real_Number, 
                     rarb$Condition,
                     p.adjust.method = "bonferroni")

rarb_test <- compare_means(Real_Number ~ Condition, comparisons = my_comparisons, p.adjust.method = "bonferroni", method='wilcox.test', data = rarb) %>% mutate(y.position = c(1.6, 2, 1.75))

ggplot(data = rarb, aes(y = Real_Number, x = Condition, colour = Group)) +
  geom_boxplot() + 
  geom_jitter() +
  xlab("Condition") + 
  ylab("Expression Level of RAR-B") + 
  scale_colour_manual(values = c("forestgreen", "navy", "firebrick")) + 
  theme(legend.title = element_blank()) +
  stat_pvalue_manual(rarb_test, label = "p.adj")
ggsave("rarb.jpg", path = "/Users/marianaurera/OneDrive - National University of Singapore/Yale-NUS/Capstone/Figures/Figure 6 (RT-qPCR)",
       width = 6.23,
      height = 3.85)
```


# STC1
```{r}
stc1_model = lm(stc1$Real_Number ~ stc1$Condition)
plot(stc1_model) # not normal
oneway.test(Real_Number ~ Condition, stc1) # unequal variances

kruskal.test(Real_Number ~ Condition, data = stc1)
pairwise.wilcox.test(stc1$Real_Number, 
                     stc1$Condition,
                     p.adjust.method = "bonferroni")

stc1_test <- compare_means(Real_Number ~ Condition, comparisons = my_comparisons, p.adjust.method = "bonferroni", method='wilcox.test', data = stc1) %>% mutate(y.position = c(3.25, 3.75, 3.5))

ggplot(data = stc1, aes(y = Real_Number, x = Condition, colour = Group)) +
  geom_boxplot() + 
  geom_jitter() +
  xlab("Condition") + 
  ylab("Expression Level of STC1") + 
  scale_colour_manual(values = c("forestgreen", "navy", "firebrick")) + 
  theme(legend.title = element_blank()) +
  stat_pvalue_manual(stc1_test, label = "p.adj")
ggsave("stc1.jpg", path = "/Users/marianaurera/OneDrive - National University of Singapore/Yale-NUS/Capstone/Figures/Figure 6 (RT-qPCR)",
       width = 6.23,
      height = 3.85)
  
```

# ZFP609
```{r}
zpf609_model = lm(zpf609$Real_Number ~ zpf609$Condition)
plot(zpf609_model) # not normal
oneway.test(Real_Number ~ Condition, zpf609) # unequal variances

kruskal.test(Real_Number ~ Condition, data = zpf609)
pairwise.wilcox.test(zpf609$Real_Number, 
                     zpf609$Condition,
                     p.adjust.method = "bonferroni")

zpf609_test <- compare_means(Real_Number ~ Condition, comparisons = my_comparisons, p.adjust.method = "bonferroni", method='wilcox.test', data = zpf609) %>% mutate(y.position = c(3.5, 4, 3.75))

ggplot(data = zpf609, aes(y = Real_Number, x = Condition, colour = Group)) +
  geom_boxplot() + 
  geom_jitter() +
  xlab("Condition") + 
  ylab("Expression Level of ZFP609") + 
  scale_colour_manual(values = c("forestgreen", "navy", "firebrick")) + 
  theme(legend.title = element_blank()) +
  stat_pvalue_manual(zpf609_test, label = "p.adj")
ggsave("zfp609.jpg", path = "/Users/marianaurera/OneDrive - National University of Singapore/Yale-NUS/Capstone/Figures/Figure 6 (RT-qPCR)",
       width = 6.23,
      height = 3.85)
  
```

Tests performed:
wilcoxon test, with bonferroni correction
alpha = 0.05
